# docker-compose.yml
version: "3.4"
services:
  app:
    build: .
    entrypoint: ./wait-for-it.sh db:5432 -t 15 -s --
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_S3_REGION_NAME:
      AWS_STORAGE_BUCKET_NAME:
      DEBUG: 1
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      MAPBOX_UPLOAD_NAME_MAIN:
      MAPBOX_UPLOAD_NAME_SIDE:
      MAPBOX_UPLOAD_NAME_SECTIONS:
      MAPBOX_UPLOAD_NAME_PROJECTS:
      MAPBOX_UPLOAD_TILESET_MAIN:
      MAPBOX_UPLOAD_TILESET_SIDE:
      MAPBOX_UPLOAD_TILESET_SECTIONS:
      MAPBOX_UPLOAD_TILESET_PROJECTS:
      PGDATABASE: docker
      PGHOST: db
      PGPASSWORD: docker
      PGUSER: docker
      TOGGLE_NEWSLETTER:
      TOGGLE_GASTRO_SIGNUPS:
      TOGGLE_GASTRO_REGISTRATIONS:
      FRONTEND_URL:
      GASTRO_SIGNUPS_OPEN:
      GASTRO_SIGNUPS_CLOSE:
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - data-volume:/var/lib/postgresql/data
volumes:
  data-volume:
