# Generated by Django 3.1.3 on 2021-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpermit',
            options={
                'ordering': ['campaign', 'title'],
                'verbose_name': 'event permit',
                'verbose_name_plural': 'event permits',
            },
        ),
        migrations.AlterField(
            model_name='eventpermit',
            name='event_end',
            field=models.TimeField(verbose_name='event end time'),
        ),
        migrations.AlterField(
            model_name='eventpermit',
            name='event_start',
            field=models.TimeField(verbose_name='event start time'),
        ),
        migrations.AlterField(
            model_name='eventpermit',
            name='setup_start',
            field=models.TimeField(verbose_name='setup start time'),
        ),
        migrations.AlterField(
            model_name='eventpermit',
            name='teardown_end',
            field=models.TimeField(verbose_name='teardown end time'),
        ),
    ]
