# Generated by Django 3.1.3 on 2021-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_use_timefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpermit',
            name='event_address',
            field=models.CharField(
                blank=True,
                help_text='street address of the event location',
                max_length=255,
                null=True,
                verbose_name='event address',
            ),
        ),
        migrations.AlterField(
            model_name='eventpermit',
            name='address',
            field=models.TextField(
                help_text='postal address of the applicant', verbose_name='address'
            ),
        ),
    ]
