# Generated by Django 2.0 on 2018-04-13 06:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('elem_nr', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('strschl', models.CharField(max_length=254)),
                ('str_name', models.CharField(max_length=254)),
                ('str_bez', models.CharField(max_length=254)),
                ('strklasse1', models.CharField(max_length=254)),
                ('strklasse', models.CharField(max_length=254)),
                ('strklasse2', models.CharField(max_length=254)),
                ('vricht', models.CharField(max_length=254)),
                ('bezirk', models.CharField(max_length=254)),
                ('stadtteil', models.CharField(max_length=254)),
                ('ebene', models.FloatField()),
                ('von_vp', models.CharField(max_length=254)),
                ('bis_vp', models.CharField(max_length=254)),
                ('laenge', models.FloatField()),
                ('gilt_von', models.FloatField()),
                ('okstra_id', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('geom_hash', models.CharField(max_length=40, null=True)),
                ('edges', models.ManyToManyField(to='fixmyapp.Edge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
