# Generated by Django 2.0 on 2018-04-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0001_initial'),
    ]

    operations = [
    ]
