# Generated by Django 2.0 on 2018-03-22 11:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('gml_parent_id', models.CharField(max_length=255)),
                ('gml_id', models.CharField(max_length=255)),
                ('spatial_geometry', models.CharField(max_length=255)),
                ('spatial_name', models.CharField(max_length=255)),
                ('spatial_name_xsi_nil', models.CharField(max_length=255)),
                ('spatial_alias', models.CharField(max_length=255)),
                ('spatial_alias_xsi_nil', models.CharField(max_length=255)),
                ('spatial_type', models.CharField(max_length=255)),
                ('spatial_type_xsi_nil', models.CharField(max_length=255)),
                ('elem_nr', models.CharField(max_length=255)),
                ('elem_nr_xsi_nil', models.CharField(max_length=255)),
                ('strschl', models.CharField(max_length=255)),
                ('strschl_xsi_nil', models.CharField(max_length=255)),
                ('str_name', models.CharField(max_length=255)),
                ('str_name_xsi_nil', models.CharField(max_length=255)),
                ('str_bez', models.CharField(max_length=255)),
                ('str_bez_xsi_nil', models.CharField(max_length=255)),
                ('strklasse1', models.CharField(max_length=255)),
                ('strklasse1_xsi_nil', models.CharField(max_length=255)),
                ('strklasse', models.CharField(max_length=255)),
                ('strklasse_xsi_nil', models.CharField(max_length=255)),
                ('strklasse2', models.CharField(max_length=255)),
                ('strklasse2_xsi_nil', models.CharField(max_length=255)),
                ('vricht', models.CharField(max_length=255)),
                ('vricht_xsi_nil', models.CharField(max_length=255)),
                ('bezirk', models.CharField(max_length=255)),
                ('bezirk_xsi_nil', models.CharField(max_length=255)),
                ('stadtteil', models.CharField(max_length=255)),
                ('stadtteil_xsi_nil', models.CharField(max_length=255)),
                ('ebene', models.CharField(max_length=255)),
                ('ebene_xsi_nil', models.CharField(max_length=255)),
                ('von_vp', models.CharField(max_length=255)),
                ('von_vp_xsi_nil', models.CharField(max_length=255)),
                ('bis_vp', models.CharField(max_length=255)),
                ('bis_vp_xsi_nil', models.CharField(max_length=255)),
                ('laenge', models.FloatField()),
                ('laenge_xsi_nil', models.CharField(max_length=255)),
                ('gilt_von', models.IntegerField()),
                ('gilt_von_xsi_nil', models.CharField(max_length=255)),
                ('okstra_id', models.CharField(max_length=255)),
                ('okstra_id_xsi_nil', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
