# Generated by Django 2.0 on 2018-04-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='PlanningSection',
        ),
    ]
