# Generated by Django 2.0 on 2018-04-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='bezirk_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='bis_vp_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='ebene_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='elem_nr_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='gilt_von_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='laenge_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='okstra_id_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='spatial_alias_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='spatial_name_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='spatial_type_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='stadtteil_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='str_bez_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='str_name_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='strklasse1_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='strklasse2_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='strklasse_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='strschl_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='von_vp_xsi_nil',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='vricht_xsi_nil',
        ),
    ]
