# Generated by Django 2.0 on 2018-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0003_auto_20180322_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edges',
            field=models.ManyToManyField(to='fixmyapp.Kanten'),
        ),
    ]
