# Generated by Django 2.0 on 2018-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0003_auto_20180404_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='gml_parent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='edge',
            name='spatial_geometry',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
