# Generated by Django 2.0 on 2018-03-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0004_project_edges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanten',
            name='id',
        ),
        migrations.AlterField(
            model_name='kanten',
            name='elem_nr',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kanten',
            name='objectid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
