# Generated by Django 2.0 on 2018-04-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0004_auto_20180404_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geom_hash',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
