# Generated by Django 2.0 on 2018-07-12 05:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0009_auto_20180620_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningsection',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
