# Generated by Django 2.0 on 2018-07-12 10:57

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0011_planningsectiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=256)),
                ('answer', markdownx.models.MarkdownxField()),
            ],
            options={'ordering': ('text',),},
        ),
    ]
