# Generated by Django 2.0 on 2018-07-12 11:36

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0012_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', markdownx.models.MarkdownxField()),
                ('short_description', models.CharField(max_length=200)),
                ('costs', models.PositiveIntegerField(blank=True, null=True)),
                ('draft', models.DateField(blank=True, null=True)),
                ('start_of_construction', models.DateField(blank=True, null=True)),
                ('completion', models.DateField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('unknown', 'unknown'), ('idea', 'idea'), (('preliminary planning',), 'preliminary planning'), (('blueprint planning',), 'blueprint planning'), ('approval planning', 'approval planning'), ('execution planning', 'execution planning'), ('preparation of awarding', 'preparation of awarding'), ('awarding', 'awarding'), ('execution of construction work', 'execution of construction work'), ('ready', 'ready')], max_length=30)),
                ('responsible', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, null=True)),
                ('cross_section_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('faq', models.ManyToManyField(blank=True, to='fixmyapp.Question')),
                ('planning_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='fixmyapp.PlanningSection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
