# Generated by Django 2.0 on 2018-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0013_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='project_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='side',
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(0, 'right'), (1, 'left')], null=True
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='completion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='draft',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='start_of_construction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
