# Generated by Django 2.0 on 2018-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0014_auto_20180712_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='planning_section',
        ),
        migrations.AddField(
            model_name='planning',
            name='planning_sections',
            field=models.ManyToManyField(to='fixmyapp.PlanningSection'),
        ),
    ]
