# Generated by Django 2.0 on 2018-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0018_planningphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='phase',
            field=models.CharField(
                choices=[
                    ('unknown', 'unknown'),
                    ('idea', 'idea'),
                    ('preliminary planning', 'preliminary planning'),
                    ('blueprint planning', 'blueprint planning'),
                    ('approval planning', 'approval planning'),
                    ('execution planning', 'execution planning'),
                    ('preparation of awarding', 'preparation of awarding'),
                    ('awarding', 'awarding'),
                    (
                        'execution of construction work',
                        'execution of construction work',
                    ),
                    ('ready', 'ready'),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='planningphoto',
            name='height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='planningphoto',
            name='src',
            field=models.ImageField(
                height_field='height',
                upload_to='photos',
                verbose_name='Image',
                width_field='width',
            ),
        ),
    ]
