# Generated by Django 2.0 on 2018-07-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0023_auto_20180727_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclingInfrastructurePhoto',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('src', models.ImageField(upload_to='', verbose_name='Photo')),
                (
                    'planning_section_detail',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='photos',
                        to='fixmyapp.PlanningSectionDetails',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
