# Generated by Django 2.0 on 2018-07-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0024_cyclinginfrastructurephoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='completion',
            new_name='construction_completed',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='start_of_construction',
            new_name='construction_started',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='draft',
            new_name='draft_submitted',
        ),
    ]
