# Generated by Django 2.0 on 2018-07-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0025_auto_20180728_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningsection',
            name='progress',
        ),
    ]
