# Generated by Django 2.0 on 2018-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0026_remove_planningsection_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsection',
            name='street_category',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
