# Generated by Django 2.0 on 2018-08-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0028_auto_20180808_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='side',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'right'), (1, 'left'), (2, 'both')], default=2
            ),
            preserve_default=False,
        ),
    ]
