# Generated by Django 2.0 on 2018-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0031_auto_20180815_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningsection',
            name='description',
        ),
        migrations.AddField(
            model_name='planningsection',
            name='suffix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to='photos', verbose_name='File'),
        ),
    ]
