# Generated by Django 2.0 on 2018-09-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0032_auto_20180830_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('new cycling infrastructure', 'new cycling infrastructure'),
                    (
                        'renovation of cycling infrastructure',
                        'renovation of cycling infrastructure',
                    ),
                    ('bike street', 'bike street'),
                    ('modification of junction', 'modification of junction'),
                    ('bike parking', 'bike parking'),
                    ('crossing aid', 'crossing aid'),
                    ('modification of cross section', 'modification of cross section'),
                    ('new street', 'new street'),
                    ('shared space', 'shared space'),
                    ('miscellaneous', 'miscellaneous'),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
