# Generated by Django 2.0 on 2018-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0034_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
