# Generated by Django 2.0.8 on 2018-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0035_auto_20181105_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='planning_sections',
            field=models.ManyToManyField(to='fixmyapp.PlanningSection'),
        ),
    ]
