# Generated by Django 2.0.8 on 2019-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0037_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
