# Generated by Django 2.0.8 on 2019-07-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0039_auto_20190530_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('verification', 'verification'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('done', 'done')], default='new', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
