# Generated by Django 2.0.8 on 2019-07-19 16:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0041_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('street_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=3, null=True)),
                ('borough', models.CharField(blank=True, max_length=255, null=True)),
                ('street_category', models.PositiveSmallIntegerField(null=True)),
                (
                    'geometry',
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        null=True, srid=4326
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
