# Generated by Django 2.0.12 on 2019-09-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0044_auto_20190913_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='borough',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='street_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
