# Generated by Django 2.0.12 on 2019-10-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0046_sectiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
