# Generated by Django 2.0.12 on 2019-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0047_project_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alert_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
