# Generated by Django 2.0.12 on 2019-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0049_auto_20191023_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='project key'),
        ),
    ]
