# Generated by Django 2.0.12 on 2019-10-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0050_auto_20191023_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_key',
            field=models.CharField(
                max_length=100, unique=True, verbose_name='project key'
            ),
        ),
    ]
