# Generated by Django 2.0.12 on 2019-10-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0051_auto_20191023_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='construction_completed',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True, verbose_name='construction completed'),
        ),
    ]
