# Generated by Django 2.0.12 on 2019-12-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0053_auto_20191028_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='planning_sections',
        ),
        migrations.RemoveField(
            model_name='planningsection',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='planningsectiondetails',
            name='planning_section',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
        migrations.DeleteModel(
            name='PlanningSection',
        ),
        migrations.DeleteModel(
            name='PlanningSectionDetails',
        ),
    ]
