# Generated by Django 2.0.12 on 2020-01-15 16:39

from datetime import date
from django.db import migrations


def fill_project_sort_field(apps, schema_editor):
    Project = apps.get_model('fixmyapp', 'Project')
    for project in Project.objects.all():
        if project.construction_completed is not None:
            year = 0
            try:
                year = int(project.construction_completed)
            except ValueError:
                pass

            if year > 1950:
                project.construction_completed_date = date(year, 12, 31)
                project.save()


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0055_project_construction_completed_date')]

    operations = [migrations.RunPython(fill_project_sort_field)]
