# Generated by Django 2.2.10 on 2020-03-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0056_auto_20200115_1639'),
    ]

    operations = [
        migrations.RemoveField(model_name='project', name='length',),
    ]
