# Generated by Django 2.2.10 on 2020-03-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0057_remove_project_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.CharField(choices=[('BIKE_STANDS', 'bike stands')], default='BIKE_STANDS', max_length=100, verbose_name='subject'),
            preserve_default=False,
        ),
    ]
