# Generated by Django 2.2.10 on 2020-03-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0058_report_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStands',
            fields=[
                (
                    'report_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='fixmyapp.Report',
                    ),
                ),
                ('number', models.PositiveSmallIntegerField()),
                ('fee_acceptable', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'bike stands',
                'verbose_name_plural': 'bike stands',
            },
            bases=('fixmyapp.report',),
        ),
    ]
