# Generated by Django 2.2.10 on 2020-03-08 09:01

from django.db import migrations


def copy_report_details(apps, schema_editor):
    Report = apps.get_model('fixmyapp', 'Report')
    BikeStands = apps.get_model('fixmyapp', 'BikeStands')
    for report in Report.objects.all():
        bike_stands = BikeStands(
            report_ptr=report,
            number=report.details['number'],
            fee_acceptable=report.details['fee_acceptable'],
        )
        bike_stands.__dict__.update(report.__dict__)
        bike_stands.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0059_bikestands'),
    ]

    operations = [
        migrations.RunPython(copy_report_details, migrations.RunPython.noop),
    ]
