# Generated by Django 2.2.10 on 2020-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0063_auto_20200318_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaystreetSignup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.CharField(max_length=64, verbose_name='campaign')),
                (
                    'street',
                    models.CharField(max_length=128, verbose_name='play_street'),
                ),
                ('first_name', models.TextField(verbose_name='first_name')),
                ('last_name', models.TextField(verbose_name='last_name')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                (
                    'tos_accepted',
                    models.BooleanField(default=False, verbose_name='tos_accepted'),
                ),
                ('captain', models.BooleanField(default=False, verbose_name='captain')),
                ('message', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'playstreet_signup',
                'verbose_name_plural': 'playstreet_signups',
                'ordering': ['campaign', 'street'],
            },
        ),
    ]
