# Generated by Django 2.2.10 on 2020-05-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0064_auto_20200409_1013'),
        ('fixmyapp', '0064_playstreetsignup'),
    ]

    operations = []
