# Generated by Django 3.0.5 on 2020-05-27 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0066_gastrosignup')]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='agreement accepted'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326, verbose_name='installation area'
            ),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='note',
            field=models.TextField(blank=True, verbose_name='note for the registrant'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='phone',
            field=models.CharField(
                max_length=32, null=True, verbose_name='telephone number'
            ),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='regulation',
            field=models.IntegerField(
                choices=[
                    (0, 'Parkplatz'),
                    (1, 'Zone 1: Dresdener Straße 13-20'),
                    (2, 'Zone 2: Dresdener Straße 119-124'),
                    (3, 'Zone 3: Simon-Dach-Straße 6-14'),
                    (4, 'Zone 4: Simon-Dach-Straße 35-41a'),
                    (5, 'Zone 5: Gabriel-Max-Straße 1-5'),
                    (6, 'Zone 6: Gabriel-Max-Straße 15-21'),
                    (7, 'Zone 7: Krossener Straße 11-21'),
                    (8, 'Zone 8: Grünberger Straße 73-79'),
                    (9, 'Zone 9: Samariterstraße 34a-37'),
                ],
                default=0,
                verbose_name='regulation',
            ),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='usage',
            field=models.TextField(null=True, verbose_name='usage'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='campaign',
            field=models.CharField(
                choices=[('xhain', 'Friedrichshain-Kreuzberg 2020')],
                max_length=32,
                verbose_name='campaign',
            ),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='category',
            field=models.CharField(
                choices=[
                    ('restaurant', 'restaurant'),
                    ('retail', 'retail'),
                    ('workshop', 'workshop'),
                    ('social', 'social'),
                    ('other', 'miscellaneous'),
                ],
                max_length=255,
                verbose_name='category',
            ),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='shop_name',
            field=models.CharField(max_length=255, verbose_name='shop name'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'new'),
                    ('verification', 'verification'),
                    ('waiting_for_application', 'waiting for application'),
                    ('application_received', 'application received'),
                    ('application_received', 'application accepted'),
                    ('application_rejected', 'application rejected'),
                ],
                default='new',
                max_length=64,
                verbose_name='status',
            ),
        ),
    ]
