# Generated by Django 3.0.5 on 2020-05-28 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0067_auto_20200527_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='area',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='installation area'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='telephone number'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='usage'),
        ),
    ]
