# Generated by Django 3.0.5 on 2020-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0068_auto_20200528_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='certificate',
            field=models.FileField(null=True, upload_to='friedrichshain-kreuzberg/certificates', verbose_name='registration certificate'),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('verification', 'verification'), ('waiting_for_application', 'waiting for application'), ('application_received', 'application received'), ('application_accepted', 'application accepted'), ('application_rejected', 'application rejected')], default='new', max_length=64, verbose_name='status'),
        ),
    ]
