# Generated by Django 3.0.5 on 2020-06-03 09:50

from django.db import migrations, models
import fixmyapp.models


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0069_auto_20200528_1228')]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='certificate',
            field=models.FileField(
                null=True,
                upload_to=fixmyapp.models.get_upload_path,
                verbose_name='registration certificate',
            ),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'new'),
                    ('verification', 'verification'),
                    ('waiting_for_application', 'waiting for application'),
                    ('application_received', 'application received'),
                    ('application_verification', 'application verification'),
                    ('application_accepted', 'application accepted'),
                    ('application_rejected', 'application rejected'),
                ],
                default='new',
                max_length=64,
                verbose_name='status',
            ),
        ),
    ]
