# Generated by Django 3.0.5 on 2020-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0071_auto_20200603_1229')]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='regulation',
            field=models.IntegerField(
                choices=[
                    (0, 'Parkplatz'),
                    (1, 'Zone 1: Dresdener Straße 13-20'),
                    (2, 'Zone 2: Dresdener Straße 119-124'),
                    (3, 'Zone 3: Simon-Dach-Straße 6-14'),
                    (4, 'Zone 4: Simon-Dach-Straße 35-41a'),
                    (5, 'Zone 5: Gabriel-Max-Straße 1-5'),
                    (6, 'Zone 6: Gabriel-Max-Straße 15-21'),
                    (7, 'Zone 7: Krossener Straße 11-21'),
                    (8, 'Zone 8: Grünberger Straße 73-79'),
                    (9, 'Zone 9: Samariterstraße 34a-37'),
                    (10, 'Gehweg'),
                    (11, 'Parken längs'),
                    (12, 'Parken quer'),
                    (13, 'Parken diagonal'),
                    (14, 'Sonstige'),
                ],
                default=0,
                verbose_name='regulation',
            ),
        )
    ]
