# Generated by Django 3.0.5 on 2020-06-16 10:31

from django.db import migrations, models
from datetime import datetime, timezone


def populate_fields(apps, schema_editor):
    GastroSignup = apps.get_model('fixmyapp', 'GastroSignup')
    for entry in GastroSignup.objects.all():
        if entry.application_received is None:
            entry.application_received = datetime(
                2020, 6, 11, 12, 00, tzinfo=timezone.utc
            )
            entry.save()


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0073_auto_20200610_1530')]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='application_decided',
            field=models.DateTimeField(null=True, verbose_name='Notice sent'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='application_received',
            field=models.DateTimeField(null=True, verbose_name='Application received'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='note_internal',
            field=models.TextField(blank=True, verbose_name='internal note'),
        ),
        migrations.RunPython(populate_fields),
    ]
