# Generated by Django 3.0.7 on 2020-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0074_auto_20200616_1031')]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='opening_hours',
            field=models.CharField(
                choices=[
                    ('weekend', 'weekend'),
                    ('workdays', 'workdays'),
                    ('whole_week', 'whole week'),
                ],
                max_length=32,
                verbose_name='opening hours',
            ),
        ),
        migrations.AlterField(
            model_name='gastrosignup',
            name='campaign',
            field=models.CharField(
                choices=[
                    ('xhain', 'Friedrichshain-Kreuzberg 2020'),
                    ('tempelberg', 'Tempelhof-Schöneberg 2020'),
                ],
                max_length=32,
                verbose_name='campaign',
            ),
        ),
    ]
