# Generated by Django 3.0.7 on 2020-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0075_auto_20200619_1035')]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='permit_check_note',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='permit check notes'
            ),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='permit_checked',
            field=models.BooleanField(default=False, verbose_name='permit checked'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='traffic_order_check_note',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='traffic order check notes',
            ),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='traffic_order_checked',
            field=models.BooleanField(
                default=False, verbose_name='traffic order checked'
            ),
        ),
    ]
