# Generated by Django 3.0.7 on 2020-07-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0076_auto_20200623_1439')]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='campaign',
            field=models.CharField(
                choices=[
                    ('xhain', 'Friedrichshain-Kreuzberg Mai 2020'),
                    ('xhain2', 'Friedrichshain-Kreuzberg Juli 2020'),
                    ('tempelberg', 'Tempelhof-Schöneberg 2020'),
                ],
                max_length=32,
                verbose_name='campaign',
            ),
        )
    ]
