# Generated by Django 3.0.7 on 2020-07-22 13:55

from django.db import migrations

replacements = {
    'Krossener Straße': 'Krossener Straße / Gabriel-Max-Straße (Boxhagener Platz)',
    'Arndtstraße': 'Chamissoplatz',
    'Paul-Lincke-Ufer': 'Paul-Lincke-Ufer / Forsterstraße',
    'Helmerdingstraße': 'Simplonstraße',
}


def update_playstreet_names(apps, schema_editor):
    PlaystreetSignup = apps.get_model('fixmyapp', 'PlaystreetSignup')
    for entry in PlaystreetSignup.objects.all():
        if entry.street in replacements.keys():
            entry.street = replacements[entry.street]
            entry.save()


class Migration(migrations.Migration):
    """Update play street names according to changes on 2020/07/21"""

    dependencies = [('fixmyapp', '0077_auto_20200722_1353')]

    operations = [migrations.RunPython(update_playstreet_names)]
