# Generated by Django 3.0.7 on 2020-08-03 10:52

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0078_auto_20200722_1355')]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='permit_end',
            field=models.DateField(null=True, verbose_name='Permit valid until'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='permit_start',
            field=models.DateField(null=True, verbose_name='Permit valid from'),
        ),
    ]
