# Generated by Django 3.0.7 on 2020-08-04 11:07

from django.db import migrations, models
import uuid


def init_keys(apps, schema_editor):
    """Initialize uuid values on new attribute

    Django doesn't use the `default` function to set values during a migration
    so this function sets these values explicitly.
    """
    GastroSignup = apps.get_model('fixmyapp', 'GastroSignup')
    for signup in GastroSignup.objects.all():
        signup.access_key_renewal = uuid.uuid4()
        signup.save()


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0079_auto_20200803_1052')]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='access_key_renewal',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(init_keys),
        migrations.AlterField(
            model_name='gastrosignup',
            name='access_key_renewal',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
