# Generated by Django 3.0.7 on 2020-08-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0080_gastrosignup_access_key_renewal')]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='renewal_application',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='previous_application',
                to='fixmyapp.GastroSignup',
                verbose_name='renewal application',
            ),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='renewal_sent_on',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='offer to apply for renewal sent on'
            ),
        ),
    ]
