# Generated by Django 3.0.7 on 2020-09-07 13:32

from django.db import migrations, models


def update_report_status(apps, schema_editor):
    """Migrate report status field to new report statuses"""

    Report = apps.get_model('fixmyapp', 'Report')

    migration_mapping = {
        'new': 'report_new',
        'verification': 'report_verification',
        'accepted': 'report_accepted',
        'rejected': 'report_rejected',
        'done': 'done',
    }

    for entry in Report.objects.all():
        if entry.status in migration_mapping.keys():
            entry.status = migration_mapping[entry.status]
            entry.save()


class Migration(migrations.Migration):

    dependencies = [('fixmyapp', '0082_auto_20200806_1103')]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('report_new', 'new'),
                    ('report_verification', 'verification'),
                    ('report_accepted', 'accepted'),
                    ('report_rejected', 'rejected'),
                    ('report_inactive', 'inactive'),
                    ('planning', 'planning'),
                    ('tender', 'tender'),
                    ('invalid', 'invalid'),
                    ('execution', 'execution'),
                    ('done', 'done'),
                ],
                default='report_new',
                max_length=20,
                null=True,
                verbose_name='status',
            ),
        ),
        migrations.RunPython(update_report_status),
    ]
