# Generated by Django 3.0.7 on 2020-09-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0083_auto_20200907_1332'),
        ('reports', '0002_import_reports'),
    ]

    operations = [
        migrations.RemoveField(model_name='report', name='user'),
        migrations.DeleteModel(name='BikeStands'),
        migrations.DeleteModel(name='Report'),
    ]
