# Generated by Django 3.0.7 on 2020-09-28 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixmyapp', '0085_bikestands_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeSetting',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('access_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('send', models.BooleanField(default=True, verbose_name='send')),
                (
                    'kind',
                    models.CharField(
                        choices=[('report_update', 'report status update')],
                        max_length=32,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notice_settings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'verbose_name': 'notice setting',
                'verbose_name_plural': 'notice settings',
                'unique_together': {('user', 'kind')},
            },
        )
    ]
