# Generated by Django 3.1.3 on 2021-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0086_noticesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_road',
            field=models.BooleanField(default=True, verbose_name='is road section'),
        ),
    ]
