# Generated by Django 3.1.3 on 2021-02-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0086_noticesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAccidents',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created date'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(auto_now=True, verbose_name='Modified date'),
                ),
                (
                    'side',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'right'), (1, 'left'), (2, 'both sides')],
                        verbose_name='side',
                    ),
                ),
                ('killed', models.IntegerField(verbose_name='killed')),
                (
                    'severely_injured',
                    models.IntegerField(verbose_name='severely injured'),
                ),
                (
                    'slightly_injured',
                    models.IntegerField(verbose_name='slightly injured'),
                ),
                (
                    'source',
                    models.TextField(blank=True, null=True, verbose_name='source'),
                ),
                (
                    'risk_level',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (3, 'accident blackspot'),
                            (2, 'some accidents'),
                            (1, 'one accident'),
                            (0, 'no accidents'),
                        ],
                        verbose_name='risk level',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Section accident data',
                'verbose_name_plural': 'Section accident datasets',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='is_road',
            field=models.BooleanField(default=True, verbose_name='is road section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='street_name',
            field=models.CharField(max_length=255, verbose_name='street name'),
        ),
        migrations.AddConstraint(
            model_name='sectiondetails',
            constraint=models.UniqueConstraint(
                fields=('section', 'side'), name='unique_section_details_dataset'
            ),
        ),
        migrations.AddField(
            model_name='sectionaccidents',
            name='section',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accidents',
                to='fixmyapp.section',
            ),
        ),
        migrations.AddConstraint(
            model_name='sectionaccidents',
            constraint=models.UniqueConstraint(
                fields=('section', 'side'), name='unique_accident_dataset'
            ),
        ),
    ]
