# Generated by Django 3.1.3 on 2021-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0087_section_accidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='followup_accepted',
            field=models.BooleanField(default=False, verbose_name='follow-up accepted'),
        ),
    ]
