# Generated by Django 3.1.3 on 2021-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0088_sectionaccidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionaccidents',
            name='risk_level',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, 'accident blackspot'),
                    (2, 'some accidents'),
                    (1, 'one accident'),
                    (0, 'no accidents'),
                ],
                verbose_name='risk level',
            ),
        ),
    ]
