# Generated by Django 3.1.3 on 2021-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0088_gastrosignup_followup_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='campaign',
            field=models.CharField(
                choices=[
                    ('xhain', 'XHain Mai 2020'),
                    ('xhain2', 'XHain Juli 2020'),
                    ('xhain3', 'XHain Verlängerungen ab Sep 2020'),
                    ('xhain2021', 'XHain 2021'),
                    ('tempelberg', 'Tempelhof-Schöneberg 2020'),
                ],
                max_length=32,
                verbose_name='campaign',
            ),
        ),
    ]
