# Generated by Django 3.1.3 on 2021-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0089_gastro_add_xhain_2021_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='campaign',
            field=models.CharField(
                choices=[
                    ('xhain', 'Xhain Mai 2020'),
                    ('xhain2', 'Xhain Juli 2020'),
                    ('xhain3', 'Xhain Verlängerungen ab Sep 2020'),
                    ('xhain2021', 'Xhain 2021'),
                    ('tempelberg', 'Tempelhof-Schöneberg 2020'),
                ],
                max_length=32,
                verbose_name='campaign',
            ),
        ),
    ]
