# Generated by Django 3.1.3 on 2021-02-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0089_auto_20210204_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaccidents',
            name='side',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'right'), (1, 'left'), (2, 'both sides')],
                default=2,
                verbose_name='side',
            ),
            preserve_default=False,
        ),
    ]
