# Generated by Django 3.1.11 on 2021-06-14 14:52

from django.db import migrations


OLD_NAME = 'Böckstraße'
NEW_NAME = 'Böckhstraße'


def rename_boekstrasse(apps, _schema_editor):
    Signup = apps.get_model('fixmyapp', 'PlaystreetSignup')
    for signup in Signup.objects.filter(street=OLD_NAME):
        signup.street = NEW_NAME
        signup.save()


def revert_rename_boekstrasse(apps, _schema_editor):
    Signup = apps.get_model('fixmyapp', 'PlaystreetSignup')
    for signup in Signup.objects.filter(street=NEW_NAME):
        signup.street = OLD_NAME
        signup.save()


class Migration(migrations.Migration):
    dependencies = [
        ('fixmyapp', '0090_gastro_filefield_max_length'),
    ]

    operations = [
        migrations.RunPython(rename_boekstrasse, revert_rename_boekstrasse),
    ]
