# Generated by Django 3.1.3 on 2021-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0091_auto_20210210_1116'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sectionaccidents',
            constraint=models.UniqueConstraint(fields=('section', 'side'), name='unique_accident_dataset'),
        ),
        migrations.AddConstraint(
            model_name='sectiondetails',
            constraint=models.UniqueConstraint(fields=('section', 'side'), name='unique_section_details_dataset'),
        ),
    ]
