# Generated by Django 3.2.5 on 2022-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0092_gastro_xhain_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastrosignup',
            name='fee_paid',
            field=models.BooleanField(default=False, verbose_name='fee paid'),
        ),
        migrations.AddField(
            model_name='gastrosignup',
            name='invoice_number',
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name='invoice number'
            ),
        ),
    ]
