# Generated by Django 3.2.5 on 2022-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixmyapp', '0093_auto_20220225_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastrosignup',
            name='campaign',
            field=models.CharField(
                choices=[
                    ('xhain', 'Xhain Mai 2020'),
                    ('xhain2', 'Xhain Juli 2020'),
                    ('xhain3', 'Xhain Verlängerungen ab Sep 2020'),
                    ('xhain2021', 'Xhain 2021'),
                    ('xhain2022', 'Xhain 2022'),
                ],
                max_length=32,
                verbose_name='campaign',
            ),
        ),
    ]
