# Generated by Django 3.0.7 on 2020-09-09 17:24


import django.db.models.deletion
import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created date'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(auto_now=True, verbose_name='Modified date'),
                ),
                (
                    'address',
                    models.TextField(blank=True, null=True, verbose_name='address'),
                ),
                (
                    'geometry',
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name='geometry'
                    ),
                ),
                (
                    'subject',
                    models.CharField(
                        choices=[('BIKE_STANDS', 'bike stands')],
                        max_length=100,
                        verbose_name='subject',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name='description',
                    ),
                ),
                (
                    'published',
                    models.BooleanField(default=True, verbose_name='published'),
                ),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('report_new', 'new'),
                            ('report_verification', 'verification'),
                            ('report_accepted', 'accepted'),
                            ('report_rejected', 'rejected'),
                            ('report_inactive', 'inactive'),
                            ('planning', 'planning'),
                            ('tender', 'tender'),
                            ('invalid', 'invalid'),
                            ('execution', 'execution'),
                            ('done', 'done'),
                        ],
                        default='report_new',
                        max_length=20,
                        null=True,
                        verbose_name='status',
                    ),
                ),
                (
                    'status_reason',
                    models.TextField(
                        blank=True, null=True, verbose_name='reason for status'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.CreateModel(
            name='BikeStands',
            fields=[
                (
                    'report_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='reports.Report',
                    ),
                ),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                (
                    'fee_acceptable',
                    models.BooleanField(default=False, verbose_name='fee_acceptable'),
                ),
            ],
            options={
                'verbose_name': 'bike stands',
                'verbose_name_plural': 'bike stands',
            },
            bases=('reports.report',),
        ),
    ]
