# Generated by Django 3.0.7 on 2020-09-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_notifications', '0002_auto_20171003_2006'),
        ('reports', '0006_report_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNotification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('report_new', 'new'),
                            ('report_verification', 'verification'),
                            ('report_accepted', 'accepted'),
                            ('report_rejected', 'rejected'),
                            ('report_inactive', 'inactive'),
                            ('planning', 'planning'),
                            ('tender', 'tender'),
                            ('invalid', 'invalid'),
                            ('execution', 'execution'),
                            ('done', 'done'),
                        ],
                        max_length=20,
                        verbose_name='status',
                    ),
                ),
                (
                    'kind',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='pinax_notifications.NoticeType',
                    ),
                ),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='reports.Report'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
