# Generated by Django 3.0.7 on 2020-09-28 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0006_report_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='origin',
            field=models.ManyToManyField(blank=True, related_name='plannings', to='reports.Report', verbose_name='origin reports'),
        ),
        migrations.CreateModel(
            name='StatusNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('status', models.CharField(choices=[('report_new', 'new'), ('report_verification', 'verification'), ('report_accepted', 'accepted'), ('report_rejected', 'rejected'), ('report_inactive', 'inactive'), ('planning', 'planning'), ('tender', 'tender'), ('invalid', 'invalid'), ('execution', 'execution'), ('done', 'done')], max_length=20, verbose_name='status')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report', verbose_name='report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'status notice',
                'verbose_name_plural': 'status notices',
            },
        ),
    ]
