# Generated by Django 3.0.7 on 2020-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('reports', '0007_statusnotification')]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='origin',
            field=models.ManyToManyField(
                blank=True,
                related_name='plannings',
                to='reports.Report',
                verbose_name='origin reports',
            ),
        )
    ]
