# Generated by Django 2.0.12 on 2019-11-13 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Session ID')),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='profile')),
                ('project', models.PositiveSmallIntegerField(verbose_name='project')),
            ],
            options={
                'verbose_name': 'survey',
                'verbose_name_plural': 'surveys',
            },
        ),
    ]
