# Generated by Django 2.0.12 on 2019-11-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('project', 'experiment', 'perspective', 'number')},
        ),
    ]
