# Generated by Django 3.1.3 on 2021-04-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200610_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='profile',
            field=models.JSONField(verbose_name='profile'),
        ),
    ]
