# Generated by Django 3.1.11 on 2021-06-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created date'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(auto_now=True, verbose_name='Modified date'),
                ),
                (
                    'affiliation',
                    models.CharField(max_length=255, verbose_name='affiliation'),
                ),
                (
                    'first_name',
                    models.CharField(max_length=255, verbose_name='first name'),
                ),
                (
                    'last_name',
                    models.CharField(max_length=255, verbose_name='last name'),
                ),
                ('role', models.CharField(max_length=255, verbose_name='role')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name='telephone number',
                    ),
                ),
                (
                    'station_name',
                    models.CharField(max_length=255, verbose_name='name of station'),
                ),
                (
                    'message',
                    models.TextField(blank=True, null=True, verbose_name='message'),
                ),
                (
                    'newsletter',
                    models.BooleanField(
                        default=True, verbose_name='requests newsletter'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                (
                    'signup_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='fahrradparken.signup',
                    ),
                ),
                ('event_id', models.IntegerField(verbose_name='event')),
                (
                    'event_title',
                    models.CharField(max_length=255, verbose_name='event title'),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('fahrradparken.signup',),
        ),
    ]
