# Generated by Django 3.1.12 on 2021-08-09 12:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import fahrradparken.models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0002_add_event_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                (
                    'created_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created date'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(auto_now=True, verbose_name='Modified date'),
                ),
                (
                    'id',
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name='station number'
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'location',
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name='geometry'
                    ),
                ),
                (
                    'travellers',
                    models.IntegerField(
                        choices=[
                            (0, 'No data available'),
                            (1, 'less than 100'),
                            (2, '100-300'),
                            (3, '301-1,000'),
                            (4, '1,001-3,000'),
                            (5, '3001-10,000'),
                            (6, '10,001-50,000'),
                            (7, 'more than 50,000'),
                        ],
                        verbose_name='traveller count',
                    ),
                ),
                (
                    'post_code',
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name='post code'
                    ),
                ),
                (
                    'is_long_distance',
                    models.BooleanField(
                        default=False, verbose_name='long distance station'
                    ),
                ),
                (
                    'is_light_rail',
                    models.BooleanField(
                        default=False, verbose_name='light rail station'
                    ),
                ),
                (
                    'is_subway',
                    models.BooleanField(default=False, verbose_name='subway station'),
                ),
                (
                    'community',
                    models.CharField(max_length=255, verbose_name='community'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyStation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created date'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(auto_now=True, verbose_name='Modified date'),
                ),
                ('survey_version', models.IntegerField(default=1)),
                ('npr', models.IntegerField(verbose_name='net promoter rating')),
                (
                    'annoyances',
                    models.CharField(max_length=32, verbose_name='annoyances'),
                ),
                (
                    'annoyance_custom',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='annoyance custom',
                    ),
                ),
                (
                    'requested_location',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='requested bike parking location',
                    ),
                ),
                (
                    'photo',
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=fahrradparken.models.SurveyStation.photo_upload_to,
                        verbose_name='photo',
                    ),
                ),
                (
                    'photo_terms_accepted',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='photo upload terms accepted',
                    ),
                ),
                (
                    'photo_description',
                    models.TextField(verbose_name='photo description'),
                ),
                (
                    'station',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='survey_responses',
                        to='fahrradparken.station',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
