# Generated by Django 3.2.4 on 2021-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0003_add_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveystation',
            name='annoyances',
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name='annoyances'
            ),
        ),
    ]
