# Generated by Django 3.2.4 on 2021-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0004_alter_surveystation_annoyances'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveystation',
            name='is_photo_published',
            field=models.BooleanField(default=False, verbose_name='photo published'),
        ),
    ]
