# Generated by Django 3.2.4 on 2021-10-05 06:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0004_alter_surveystation_annoyances'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingFacility',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Created date'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(auto_now=True, verbose_name='Modified date'),
                ),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                (
                    'confirmations',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='confirmations'
                    ),
                ),
                ('covered', models.BooleanField(null=True, verbose_name='covered')),
                (
                    'external_id',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='external ID',
                    ),
                ),
                (
                    'location',
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name='location'
                    ),
                ),
                (
                    'parking_garage',
                    models.BooleanField(
                        null=True, verbose_name='part of parking garage'
                    ),
                ),
                ('secured', models.BooleanField(null=True, verbose_name='secured')),
                (
                    'source',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='source'
                    ),
                ),
                ('stands', models.BooleanField(null=True, verbose_name='stands')),
                ('two_tier', models.BooleanField(null=True, verbose_name='two tier')),
                (
                    'type',
                    models.IntegerField(
                        choices=[
                            (0, 'enclosed compound'),
                            (1, 'bicycle locker'),
                            (2, 'bicycle parking tower'),
                        ]
                    ),
                ),
                (
                    'station',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parking_facilities',
                        to='fahrradparken.station',
                    ),
                ),
            ],
            options={
                'verbose_name': 'parking facility',
                'verbose_name_plural': 'parking facilities',
            },
        ),
        migrations.CreateModel(
            name='ParkingFacilityOccupancy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'value',
                    models.IntegerField(
                        choices=[
                            (0, 'overcapacity'),
                            (1, 'high'),
                            (2, 'medium'),
                            (3, 'low'),
                        ]
                    ),
                ),
                (
                    'parking_facility',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fahrradparken.parkingfacility',
                    ),
                ),
            ],
            options={
                'verbose_name': 'occupancy',
            },
        ),
        migrations.CreateModel(
            name='ParkingFacilityCondition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'value',
                    models.IntegerField(
                        choices=[
                            (0, 'very bad'),
                            (1, 'bad'),
                            (2, 'good'),
                            (3, 'very good'),
                        ]
                    ),
                ),
                (
                    'parking_facility',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fahrradparken.parkingfacility',
                    ),
                ),
            ],
            options={
                'verbose_name': 'condition',
            },
        ),
    ]
