# Generated by Django 3.2.4 on 2021-10-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0005_surveystation_is_photo_published'),
        ('fahrradparken', '0006_parkingfacilityphoto'),
    ]

    operations = [
    ]
