# Generated by Django 3.2.4 on 2021-11-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0007_merge_tips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveystation',
            options={
                'verbose_name': 'Station survey',
                'verbose_name_plural': 'Station surveys',
            },
        ),
    ]
