# Generated by Django 3.2.4 on 2021-11-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0009_alter_parkingfacility_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingfacilityphoto',
            old_name='src',
            new_name='photo_url',
        ),
    ]
