# Generated by Django 3.2.4 on 2021-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0010_rename_src_parkingfacilityphoto_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingfacility',
            name='external_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='external ID',
            ),
        ),
    ]
