# Generated by Django 3.2.4 on 2021-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0012_alter_parkingfacility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingfacilityphoto',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
    ]
