# Generated by Django 3.2.4 on 2021-12-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0014_alter_parkingfacility_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingfacility',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
