# Generated by Django 3.2.5 on 2021-12-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0015_parkingfacility_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'station', 'verbose_name_plural': 'stations'},
        ),
        migrations.AlterField(
            model_name='parkingfacility',
            name='external_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='facility ID',
            ),
        ),
        migrations.AlterField(
            model_name='parkingfacilityphoto',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='photo published'),
        ),
    ]
