# Generated by Django 3.2.5 on 2021-12-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0017_parkingfacility_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingfacility',
            name='station',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='parking_facilities',
                to='fahrradparken.station',
                verbose_name='station',
            ),
        ),
        migrations.AlterField(
            model_name='parkingfacility',
            name='type',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 'enclosed compound'),
                    (1, 'bicycle locker'),
                    (2, 'bicycle parking tower'),
                ],
                null=True,
                verbose_name='type',
            ),
        ),
    ]
