# Generated by Django 3.2.5 on 2021-12-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrradparken', '0018_auto_20211211_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingfacilityphoto',
            name='terms_accepted',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='upload terms accepted'
            ),
        ),
    ]
